## Import Tools

In [2]:
import csv
import datetime
import numpy as np
import sklearn.linear_model as sklin
import sklearn.svm as sksvm
import sklearn.metrics as skmet
import sklearn.ensemble as skens
import sklearn.cross_validation as skcv
import sklearn.grid_search as skgs
import sklearn.preprocessing as skpr
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error

## Data Fetching

#### Alternative 1

In [3]:
data = lisData.LisData('train.csv',15,1)
print(data.data[34].x)

NameError: name 'lisData' is not defined

#### Alternative 2

In [109]:
trainx = []
trainy = []
testx = []
nOutput = 1
nInput = 15
with open('train.csv','r') as inputFile:
    leReader = csv.reader(inputFile)
    next(leReader)
    for row in leReader:
        id = int(row[0])
        y = np.array(row[1:nOutput+1]).astype(np.float)
        x = np.array(row[nOutput+1:nInput+nOutput+1]).astype(np.float)
        trainx.append(x)
        trainy.append(y)
        
with open('test.csv','r') as inputFile:
    leReader = csv.reader(inputFile)
    next(leReader)
    for row in leReader:
        id = int(row[0])
        x = np.array(row[1:nInput+1]).astype(np.float)
        testx.append(x)

print(trainx[34])
print(testx[34])

[ 1.89526027  2.37496407 -0.33221165 -0.96862469  0.33994368  1.17581895
  1.49869027  2.04797216  1.28427967  2.74266878  0.77739432  0.08692078
 -0.68121822  0.11102864  1.24211796]
[ 0.62222615  0.24094433  0.98483006  0.11788056  1.59518869  0.91472915
  1.97502096 -1.02646307  1.32399956 -0.54682658  0.39639841  2.27331498
  0.48291622  2.38862851  3.01288612]


## Actual Fitting

In [22]:
clf = sklin.LinearRegression()
clf.fit (trainx, trainy)
clf.coef_
testy = clf.predict(testx)

print(testy)

[[  7.29022687]
 [-34.4230165 ]
 [ 82.29394959]
 ..., 
 [ 98.66763217]
 [ 90.16475902]
 [ -7.44481286]]


In [51]:
clf = sklin.Ridge (alpha = 0.1)
clf.fit (trainx, trainy)
clf.coef_
predicty = clf.predict(trainx)
testy = clf.predict(testx)
print(score(trainy,predicty))
print(testy)

37.1268828115
[[  7.29382659]
 [-34.41587605]
 [ 82.28696405]
 ..., 
 [ 98.66067416]
 [ 90.15827212]
 [ -7.44084178]]


In [53]:
def RMSE(y, ypred):
    return mean_squared_error(y, ypred)**0.5
scorefun = skmet.make_scorer(score)
scores = skcv.cross_val_score(clf, trainx, trainy, scoring=scorefun, cv=900)
print(scores)
print(np.mean(scores))
print(np.std(scores))

[  1.45628118e+01   1.22188199e+01   7.86744733e+00   2.42048995e+01
   5.53057344e+01   3.37015797e+01   4.44316996e+01   7.26875050e+01
   6.49188908e+00   3.18318323e+01   7.02584958e+01   5.55750910e+00
   2.96824700e+01   4.27474935e+01   6.56764950e+00   3.46319843e+00
   1.68061931e+01   2.68032785e+00   3.57901860e+01   2.88953244e+01
   3.79654008e+01   3.68094829e+00   1.35549348e+01   9.09982342e+00
   2.90848167e+00   1.26391051e+01   6.91654592e+00   1.87977310e+01
   7.69955809e+00   2.75486491e+01   2.22287183e+01   6.67164794e+01
   1.83188370e+01   6.26821490e-01   2.49811764e+01   4.09973377e+01
   5.58809981e+00   2.46581535e+01   3.59964007e+01   1.48104481e+01
   4.71501857e+00   1.40384052e+01   2.73164796e+01   1.81040370e+01
   2.08341741e+01   9.59268824e+00   4.65391523e+01   9.48459321e+00
   3.70639438e+01   1.09475356e+01   1.60639183e+01   6.90799040e+00
   1.04439708e+01   1.74542305e+01   3.18898460e+01   2.49045554e+01
   5.39832594e+00   1.26398377e+01

In [54]:
min(scores)

0.0026762826191362166

In [89]:
a=[[1,2],[3,4],[5,6]]
sinustrans = skpr.FunctionTransformer(np.sin)
xsinus = sinustrans.fit_transform(a)
print(xsinus)
costrans = skpr.FunctionTransformer(np.cos)
xcosine = costrans.fit_transform(a)
print(xcosine)
logtrans = skpr.FunctionTransformer(np.log)
xlog = logtrans.fit_transform(a)
print(xlog)

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]
[[ 0.          0.69314718]
 [ 1.09861229  1.38629436]
 [ 1.60943791  1.79175947]]


### Finding best degree K

In [94]:
Kscores = []
def rmse(y, ypred):
    return mean_squared_error(y, ypred)**0.5
RMSE = skmet.make_scorer(rmse)
sinustrans = skpr.FunctionTransformer(np.sin)
xsinus = sinustrans.fit_transform(trainx)
costrans = skpr.FunctionTransformer(np.cos)
xcosine = costrans.fit_transform(trainx)
#logtrans = skpr.FunctionTransformer(np.log)
#xlog = logtrans.fit_transform(trainx)
for K in range(4):
    poly = skpr.PolynomialFeatures(K)
    xtrainingpoly = poly.fit_transform(trainx)

    
    print(xtrainingpoly.shape, xsinus.shape, xcosine.shape)# xlog.shape)
    
    xtraining = np.hstack((xtrainingpoly, xsinus, xcosine))# xlog))

    clf = sklin.RidgeCV(scoring=RMSE)

    # Evaluate the models using crossvalidation
    scores = skcv.cross_val_score(clf,xtraining, trainy, scoring=RMSE, cv=900)
    
    
    print(K)
    print(np.mean(scores))
    print(scores)
    print(np.std(scores))
    Kscores.append([np.mean(scores),np.std(scores)])
    


(900, 1) (900, 15) (900, 15)
0
27.6433515677
[  8.52041141e+00   1.41190218e+01   2.46812773e+01   2.30925293e+01
   3.74184981e+01   2.92066169e+01   2.32100723e+01   8.39272322e+01
   1.97045004e+00   3.28789676e+01   5.69934200e+01   3.35204804e-01
   5.04832625e-01   3.84635840e+01   1.02057075e+01   4.21444031e+01
   1.23538077e+00   1.94748140e+01   6.41050165e+01   7.83784169e+00
   3.37711985e+01   2.27873956e+01   9.41746666e+00   2.21140585e+01
   1.84727595e+01   6.33984486e+00   2.75245178e+01   2.53875112e+01
   1.35230853e+01   3.15918327e+01   4.19029661e+01   8.15766193e+01
   2.07000100e+00   2.38612635e+01   3.29336624e+01   5.77000207e+01
   3.49121049e-01   1.79674170e+01   2.83623510e+01   5.39181750e+00
   2.37160111e+00   2.13063302e+00   2.35369784e+01   1.94069371e+00
   2.44872607e+01   1.96831175e+01   2.77249551e+01   1.34005711e+01
   5.26048753e+01   1.21135537e+01   1.87877263e+01   3.56809563e+01
   1.13224443e+01   2.99042525e+01   6.97092476e+00   3.46

KeyboardInterrupt: 

### Working with degree K=2

In [123]:
def rmse(y, ypred):
    return mean_squared_error(y, ypred)**0.5
def root(x):
    return np.sqrt(abs(x))
def lgrthm(x):
    return np.log(abs(x))
RMSE = skmet.make_scorer(rmse)
poly = skpr.PolynomialFeatures(2)
xtrainingpoly = poly.fit_transform(trainx)
sinustrans = skpr.FunctionTransformer(np.sin)
xsinus = sinustrans.fit_transform(trainx)
costrans = skpr.FunctionTransformer(np.cos)
xcosine = costrans.fit_transform(trainx)
sqrttrans = skpr.FunctionTransformer(root)
xsqrt = sqrttrans.fit_transform(trainx)
logtrans = skpr.FunctionTransformer(lgrthm)
xlog = logtrans.fit_transform(trainx)
    
xtraining = np.hstack((xtrainingpoly, xsinus, xcosine, xsqrt, xlog))

#clf = sklin.RidgeCV(alphas=(0.00001,0.0001,100.00001),scoring=RMSE,cv=900)
#clf = sklin.LinearRegression()
#clf = sksvm.SVR(kernel='linear')
params = {'n_estimators': 500, 'max_depth': 4, 'min_samples_split': 1,'learning_rate': 0.01, 'loss': 'ls'}
clf = skens.GradientBoostingRegressor(**params)

ytraining = np.ravel(trainy)
clf.fit(xtraining,ytraining)

xtestingpoly = poly.fit_transform(testx)
xtestingsinus = sinustrans.fit_transform(testx)
xtestingcosine = costrans.fit_transform(testx)
xtestingsqrt = sqrttrans.fit_transform(testx)
xtestinglog = logtrans.fit_transform(testx)
    
xtesting = np.hstack((xtestingpoly, xtestingsinus, xtestingcosine, xtestingsqrt, xtestinglog))
testy = clf.predict(xtesting)
print(rmse(trainy,clf.predict(xtraining)))

16.4141497359


## Writing Results

In [124]:
now =datetime.datetime.now()
with open('output_{0}.csv'.format(now.strftime('%Y%m%d%H%M')), 'w') as outFile:
    outFile.write('Id,y\n')
    for idx,testyelem in enumerate(testy):
        #outFile.write("%d,%s\n"%(idx+900,format(testyelem,'.30f')))    
        outFile.write("%d,%.100f\n"%(idx+900,testyelem))